version: '3.9'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: slidegenie_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-slidegenie}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-slidegenie_password}
      POSTGRES_DB: ${POSTGRES_DB:-slidegenie}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-slidegenie} -d ${POSTGRES_DB:-slidegenie}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - slidegenie_network

  redis:
    image: redis:7-alpine
    container_name: slidegenie_redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - slidegenie_network

  minio:
    image: minio/minio:latest
    container_name: slidegenie_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - slidegenie_network

  minio-init:
    image: minio/mc:latest
    container_name: slidegenie_minio_init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY:-minioadmin} ${MINIO_SECRET_KEY:-minioadmin};
      /usr/bin/mc mb --ignore-existing myminio/${MINIO_BUCKET_NAME:-slidegenie};
      /usr/bin/mc anonymous set download myminio/${MINIO_BUCKET_NAME:-slidegenie}/public;
      exit 0;
      "
    networks:
      - slidegenie_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slidegenie_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./alembic:/app/alembic
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - MINIO_ENDPOINT=minio:9000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - slidegenie_network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  slidegenie_network:
    driver: bridge